services:
  # DATABASE
  # postgres-db:
  #   container_name: postgres-db
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - ./volumes/postgres:/var/lib/postgresql/data
  #   ports:
  #     - ${DB_OUTSIDE_PORT:-5432}:5432
  #   environment:
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_DATABASE}

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # - ./volumes/postgres:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80" # pgAdmin accesible en localhost:8080
    depends_on:
      - postgres

  # BACKEND
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src # monta el código fuente
      - /usr/src/app/node_modules # evita que node_modules se pisen
    command: npm run start:dev
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  pgadmin_data:

  # BACKEND
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ./backend/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=${BACKEND_PORT}
  #     - DATABASE_URL=${DB_URL}
  #   depends_on:
  #     - postgres

  # WEB CLIENT
  # web-client:
  #   build:
  #     context: ./frontend
  #     dockerfile: docker/Dockerfile
  #   ports:
  #     - ${WEB_CLIENT_OUTSIDE_PORT:-8080}:80
  #   volumes:
  #     - ./frontend/src:/app/src
  #   command: npm start
